# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DCWear' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for DCWear
  pod 'Alamofire',
  :git => 'https://github.com/Alamofire/Alamofire.git',
  :branch => 'swift3'

end
